#!/bin/bash
# docker run --name jelly-proxy -d --restart always cloudflare/cloudflared:latest tunnel --no-autoupdate run --token eyJhIjoiNmM5NTEzMDcyMGY2ZWUyM2IxMmRiZjY4MTliNDU3NzMiLCJ0IjoiNDEyZTVmNTMtYmUxMC00MzY1LWE1YzAtNThmMjg0MjExNDIxIiwicyI6IllqRXlaV0V6TkRBdFlXSXdaUzAwWkRkbUxXSmpPV0l0TmpSbU1USXdOakEzTURrMCJ9
docker run --name site-dev-proxy -d --restart always cloudflare/cloudflared:latest tunnel --no-autoupdate run --token $CLOUDFLARE_TUNNEL_TOKEN
docker run --name openwebui-proxy -d --restart always cloudflare/cloudflared:latest tunnel --no-autoupdate run --token $CLOUDFLARE_TUNNEL_TOKEN
docker run --name minio-proxy -d --restart always cloudflare/cloudflared:latest tunnel --no-autoupdate run --token $CLOUDFLARE_TUNNEL_TOKEN
docker run --name chatwoot-proxy -d --restart always cloudflare/cloudflared:latest tunnel --no-autoupdate run --token $CLOUDFLARE_TUNNEL_TOKEN
# docker run --name typebot-proxy -d --restart always cloudflare/cloudflared:latest tunnel --no-autoupdate run --token $CLOUDFLARE_TUNNEL_TOKEN
# docker run --name bottypebot-proxy -d --restart always cloudflare/cloudflared:latest tunnel --no-autoupdate run --token $CLOUDFLARE_TUNNEL_TOKEN
# docker run --name jitsi-proxy -d --restart always cloudflare/cloudflared:latest tunnel --no-autoupdate run --token $CLOUDFLARE_TUNNEL_TOKEN
docker run --name langflow-proxy -d --restart always cloudflare/cloudflared:latest tunnel --no-autoupdate run --token $CLOUDFLARE_TUNNEL_TOKEN
docker run --name nextcloud-proxy -d --restart always cloudflare/cloudflared:latest tunnel --no-autoupdate run --token $CLOUDFLARE_TUNNEL_TOKEN
docker run --name evolution-proxy -d --restart always cloudflare/cloudflared:latest tunnel --no-autoupdate run --token $CLOUDFLARE_TUNNEL_TOKEN
docker run --name minioapi-proxy -d --restart always cloudflare/cloudflared:latest tunnel --no-autoupdate run --token $CLOUDFLARE_TUNNEL_TOKEN
docker run --name site-prod-proxy -d --restart always cloudflare/cloudflared:latest tunnel --no-autoupdate run --token $CLOUDFLARE_TUNNEL_TOKEN
docker run --name ollama-proxy  -d --restart always cloudflare/cloudflared:latest tunnel --no-autoupdate run --token $CLOUDFLARE_TUNNEL_TOKEN
