version: "3.8"

networks:
  comfyui_network:
    driver: bridge
    name: comfyui_network

services:
  comfyui:
    image: ghcr.io/cyntachs/comfy-webui-docker:main
    container_name: comfyui
    ports:
      - "9897:5555"
    volumes:
      - /home/magus/comfy:/stable-diffusion
    env_file:
      - ./env_files/comfyui-neo.env
    networks:
      - comfyui_network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [compute, utility]