version: "3.8"

networks:
  dockge_network:
    driver: bridge
    name: dockge_network

services:
  dockge:
    image: louislam/dockge:1
    container_name: dockge
    restart: unless-stopped
    ports:
      - "5001:5001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - /opt/stacks:/opt/stacks
    env_file:
      - ./env_files/dockge.env
    networks:
      - dockge_network