version: "3.8"

networks:
  homepage_network:
    driver: bridge
    name: homepage_network

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    env_file:
      - ./env_files/homepage.env
    ports:
      - "3077:3000"
    volumes:
      - ./config:/app/config
    networks:
      - homepage_network
    restart: unless-stopped
