version: "3.8"

networks:
  jellyfin_network:
    driver: bridge
    name: jellyfin_network

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    env_file:
      - ./env_files/jellyfin.env
    volumes:
      - ~/apps_data/jellyfin_config:/config
      - ~/media/series:/data/tvshows
      - ~/media/movies:/data/movies
      - ~/media/youtube:/data/youtube
    ports:
      - "8096:8096"
    restart: unless-stopped
    networks:
      - jellyfin_network