version: "3.8"

networks:
  kasm_network:
    driver: bridge
    name: kasm_network

services:
  kasm:
    image: lscr.io/linuxserver/kasm:latest
    container_name: kasm
    privileged: true
    env_file:
      - ./env_files/kasm-workspaces.env
    volumes:
      - /root/apps_data/kasm/data:/opt
    ports:
      - "3000:3000"
      - "8443:443"
    restart: unless-stopped
    networks:
      - kasm_network