version: "3.8"

networks:
  kavita_network:
    driver: bridge
    name: kavita_network

services:
  kavita:
    image: jvmilazz0/kavita:latest
    container_name: kavita
    volumes:
      - /root/media/manga:/manga
      - /root/media/comics:/comics
      - /root/media/books:/books
      - /root/apps_data/kavita:/kavita/config
    env_file:
      - ./env_files/kavita.env
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - kavita_network