version: "3.8"

networks:
  kokoro_network:
    driver: bridge
    name: kokoro_network

services:
  kokoro:
    image: ghcr.io/remsky/kokoro-fastapi-gpu:v0.1.4
    container_name: kokoro
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    ports:
      - "8880:8880"
    networks:
      - kokoro_network