version: "3.8"

networks:
  langflow_network:
    driver: bridge
    name: langflow_network

services:
  langflow:
    image: langflowai/langflow:latest
    container_name: langflow
    env_file:
      - ./env_files/langflow.env
    ports:
      - "7860:7860"
    tty: true
    stdin_open: true
    restart: unless-stopped
    networks:
      - langflow_network