version: '3.8'

networks:
  librechat_network:
    driver: bridge
    name: librechat_network

services:
  mongodb:
    image: mongo:latest
    container_name: librechat-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: magus
      MONGO_INITDB_ROOT_PASSWORD: senhamagus123!
    volumes:
      - librechat_mongodb_data:/data/db
    networks:
      - librechat_network

  vectordb:
    image: ankane/pgvector:latest
    container_name: librechat-vectordb
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    restart: always
    volumes:
      - librechat_vectordb_data:/var/lib/postgresql/data
    networks:
      - librechat_network

  api:
    container_name: LibreChat
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mongodb
      - vectordb
      - rag_api
    image: ghcr.io/danny-avila/librechat-dev:latest
    restart: always
    user: ${UID}:${GID}
    extra_hosts:
      - host.docker.internal:host-gateway
    env_file:
      - ./env_files/librechat.env
    environment:
      - UID=${UID:-1000}
      - GID=${GID:-1000}
    volumes:
      - type: bind
        source: ./.env
        target: /app/.env
      - ./images:/app/client/public/images
      - ./logs:/app/api/logs
      - type: bind
        source: ./librechat.yaml
        target: /app/librechat.yaml
    networks:
      - librechat_network

  meilisearch:
    container_name: chat-meilisearch
    image: getmeili/meilisearch:v1.7.3
    restart: always
    user: ${UID}:${GID}
    env_file:
      - ./env_files/librechat.env
    volumes:
      - ./meili_data_v1.7:/meili_data
    networks:
      - librechat_network

  rag_api:
    container_name: rag_api
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
    env_file:
      - ./env_files/librechat.env
      - .env
    restart: always
    depends_on:
      - vectordb
    networks:
      - librechat_network

volumes:
  librechat_mongodb_data:
  librechat_vectordb_data: