version: "3.8"

networks:
  litellm_network:
    driver: bridge
    name: litellm_network

services:
  litellm:
    image: ghcr.io/berriai/litellm:main-stable
    container_name: litellm
    restart: always
    volumes:
      - ./config.yaml:/app/config.yaml
    command:
      - --config=/app/config.yaml
    ports:
      - "4000:4000"
    env_file:
      - ./env_files/litellm.env
      - .env
    depends_on:
      - db
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:4000/health/liveliness || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - litellm_network

  db:
    image: postgres:16
    container_name: litellm-db
    restart: always
    environment:
      POSTGRES_DB: litellm
      POSTGRES_USER: llmproxy
      POSTGRES_PASSWORD: dbpassword9090
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -d litellm -U llmproxy
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - litellm_network

  prometheus:
    image: prom/prometheus
    container_name: litellm-prometheus
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9092:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=15d
    restart: always
    networks:
      - litellm_network

volumes:
  prometheus_data:
    driver: local
  postgres_data:
    name: litellm_postgres_data