version: "3.8"

networks:
  n8n_network:
    driver: bridge
    name: n8n_network

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    env_file:
      - ./env_files/n8n.env
    volumes:
      - ./n8n_data:/home/node/.n8n
    networks:
      - n8n_network