version: "3.8"

networks:
  neo4j_network:
    driver: bridge
    name: neo4j_network

services:
  neo4j:
    image: neo4j:5.14.0
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ~/apps_data/neo4j_config/data:/data
      - ~/apps_data/neo4j_config/logs:/logs
      - ~/apps_data/neo4j_config/import:/import
    env_file:
      - ./env_files/neo4j.env
    networks:
      - neo4j_network