version: "3.8"

networks:
  ollama_network:
    driver: bridge
    name: ollama_network

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    volumes:
      - /root/.ollama:/root/.ollama
    ports:
      - "11434:11434"
    env_file:
      - ./env_files/ollama.env
    restart: unless-stopped
    networks:
      - ollama_network