version: "3.8"

networks:
  tubearchivist_network:
    driver: bridge
    name: tubearchivist_network

services:
  tubearchivist:
    container_name: tubearchivist
    restart: unless-stopped
    image: bbilly1/tubearchivist
    ports:
      - "8000:8000"
    volumes:
      - ~/media/youtube:/youtube
      - cache:/cache
    env_file:
      - ./env_files/tubearchivist.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      - archivist-es
      - archivist-redis
    networks:
      - tubearchivist_network

  archivist-redis:
    image: redis/redis-stack-server
    container_name: archivist-redis
    restart: unless-stopped
    volumes:
      - redis:/data
    depends_on:
      - archivist-es
    networks:
      - tubearchivist_network

  archivist-es:
    image: bbilly1/tubearchivist-es
    container_name: archivist-es
    restart: unless-stopped
    env_file:
      - ./env_files/tubearchivist.env
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es:/usr/share/elasticsearch/data
    networks:
      - tubearchivist_network

volumes:
  media:
  cache:
  redis:
  es: