version: '3.8'

networks:
  typebot_network:
    driver: bridge
    name: typebot_network

services:
  typebot-db:
    image: postgres:14-alpine
    container_name: typebot-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: typebot
      POSTGRES_PASSWORD: typebot
      POSTGRES_DB: typebot
    volumes:
      - typebot_db_data:/var/lib/postgresql/data
    networks:
      - typebot_network

  typebot-builder:
    image: maguscorp/typebot-builder:latest
    restart: always
    depends_on:
      - typebot-db
    ports:
      - '8082:3000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file: ./env_files/typebot.env
    networks:
      - typebot_network

  typebot-viewer:
    image: maguscorp/typebot-viewer:latest
    restart: always
    depends_on:
      - typebot-db
    ports:
      - '8081:3000'
    env_file: ./env_files/typebot.env
    networks:
      - typebot_network

volumes:
  typebot_db_data: