version: "3.8"

networks:
  uptime_network:
    driver: bridge
    name: uptime_network

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1.20.2
    container_name: uptime-kuma
    volumes:
      - ./uptime-kuma-data:/app/data
    ports:
      - "3001:3001"
    restart: always
    networks:
      - uptime_network