version: "3.8"

networks:
  whisper_network:
    driver: bridge
    name: whisper_network

services:
  whisper:
    image: onerahmet/openai-whisper-asr-webservice:latest-gpu
    container_name: whisper
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    ports:
      - "9000:9000"
    env_file:
      - ./env_files/whisper.env
    volumes:
      - ./whisper_models:/root/.cache/whisper
    networks:
      - whisper_network