#!/usr/bin/env python3

import os
from pathlib import Path
import subprocess
import gumpython
from ruamel.yaml import YAML

# --- Configuration ---
HOME = Path.home()
NMDE_DIR = HOME / ".local/share/nmde"
COMPOSE_DIR = NMDE_DIR / "composes"
STATE_FILE = COMPOSE_DIR / ".state"
ENV_DIR = COMPOSE_DIR / "env_files"
DB_FILE = ENV_DIR / "envs.db"

yaml = YAML()

# --- Helper Functions ---
def get_compose_files():
    """Returns a sorted list of all .yaml and .yml files in the compose directory."""
    return sorted([p.name for p in COMPOSE_DIR.glob("*.yaml")] + [p.name for p in COMPOSE_DIR.glob("*.yml")])

def get_up_services():
    """Returns a set of services that are currently marked as 'up' in the state file."""
    if not STATE_FILE.exists():
        return set()
    with open(STATE_FILE, "r") as f:
        return set(line.strip() for line in f)

def save_up_services(services):
    """Saves the set of 'up' services to the state file."""
    with open(STATE_FILE, "w") as f:
        for service in sorted(list(services)):
            f.write(f"{service}\n")

def generate_env_file(service_name):
    """Generates a .env file for a service from the SQLite database."""
    env_file_path = ENV_DIR / f"{service_name}.env"
    with open(env_file_path, "w") as f:
        f.write(f"# Auto-generated by nmde-composes on {os.popen('date').read().strip()}\n")
        # This requires the env_manager.py script to be in the same directory
        from env_manager import list_vars
        variables = list_vars(service_name)
        for key, value in variables.items():
            f.write(f'{key}="{value}"\n')

def run_docker_compose(args):
    """Runs a docker-compose command."""
    try:
        subprocess.run(["docker-compose"] + args, check=True, capture_output=True, text=True)
    except subprocess.CalledProcessError as e:
        print(f"Error running docker-compose: {e.stderr}")
        gumpython.spin(spinner="points", time=2)


# --- Main Application Logic ---
def sync_composes(services_to_be_up):
    """Brings services up or down to match the desired state."""
    currently_up = get_up_services()
    
    # Bring up services
    for service in services_to_be_up:
        if service not in currently_up:
            print(f"Bringing up {service}...")
            service_name = Path(service).stem
            generate_env_file(service_name)
            run_docker_compose(["-f", str(COMPOSE_DIR / service), "up", "-d", "--remove-orphans"])

    # Bring down services
    for service in currently_up:
        if service not in services_to_be_up:
            print(f"Bringing down {service}...")
            run_docker_compose(["-f", str(COMPOSE_DIR / service), "down", "--remove-orphans"])

    save_up_services(services_to_be_up)

def main_menu():
    """The main interactive menu."""
    up_services = get_up_services()
    
    while True:
        os.system("clear")
        choices = []
        all_services = get_compose_files()
        
        for service in all_services:
            prefix = "✓" if service in up_services else " "
            choices.append(f"{prefix} {service}")
        
        choices.extend(["", "[Sync and Exit]", "[Cancel]"])

        selected = gumpython.choose(choices, header="Select a service to open its menu.", no_limit=True)

        if not selected or "[Cancel]" in selected:
            break
        
        if "[Sync and Exit]" in selected:
            sync_composes(up_services)
            gumpython.spin(title="Sync complete!", spinner="globe", time=1)
            break

        # This part handles toggling. It's a bit complex due to gum's output.
        toggled_service_name = selected[0].strip().split(" ", 1)[1]
        
        sub_choice = gumpython.choose(["Toggle On/Off", "Edit Environment"])
        if sub_choice == "Toggle On/Off":
            if toggled_service_name in up_services:
                up_services.remove(toggled_service_name)
            else:
                up_services.add(toggled_service_name)
        elif sub_choice == "Edit Environment":
            # This requires the env_manager.py script to be callable with a service name
            subprocess.run(["./spells/env_manager.py", Path(toggled_service_name).stem])


if __name__ == "__main__":
    main_menu()
